---
name: Student
options:
  groupSortPosition: top
  bundleIdPrefix: com.instructure.icanvas.2u
  deploymentTarget:
    iOS: 16.0
  createIntermediateGroups: true
settings:
  CODE_SIGN_STYLE: Automatic ## This line is removed in the project-ci.yml file so Bitrise can manage code sign. 
  DEVELOPMENT_TEAM: 58GH9WB284 ## This line is removed in the project-ci.yml file so Bitrise can manage code sign.
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  LOCALIZATION_PREFERS_STRING_CATALOGS: true
  CURRENT_PROJECT_VERSION: 28
  MARKETING_VERSION: 1.6
  platform: iOS
  DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
sources:
  - path: ./
    excludes:
      - ".swiftlint.yml"
include:
  - Student/student.yml
  - SubmitAssignment/student-submit-assignment.yml
  - Widgets/student-widgets.yml
  - StudentE2ETests/student-e2e-tests.yml
  - StudentUnitTests/student-unit-tests.yml
projectReferences:
  CanvasCore:
    path: ../CanvasCore/CanvasCore.xcodeproj
  Core:
    path: ../Core/Core.xcodeproj
packages:
  Heap:
    url: https://github.com/heap/heap-ios-sdk.git
    exactVersion: 9.1.0
  PSPDFKit:
    url: https://github.com/PSPDFKit/PSPDFKit-SP
    exactVersion: 13.0.1
  BugfenderLibrary:
    url: https://github.com/bugfender/BugfenderSDK-iOS
    exactVersion: 1.13.2
  AWSSDK:
    url: https://github.com/aws-amplify/aws-sdk-ios-spm
    exactVersion: 2.33.10
